version: "3.8"
services:
  grpc-service:
    build: ./service
    environment:
      GRPC_PORT: 9080
  grpc-client:
    build: ./client
    environment:
      settings.grpc.host: grpc-service
      settings.grpc.port: 9080